Week3 (2)
data cleaning:

In [1]:
import numpy as np
import pandas as pd

In [28]:
chipotle_df = pd.read_csv("/content/sample_data/chipotle.tsv",sep='\t')

In [29]:
chipotle_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [30]:
chipotle_df.shape

(4622, 5)

In [31]:
chipotle_df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [33]:
chipotle_df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:


# Example: Handling missing values by filling them with a default value (e.g., "Unknown")
# Replace NaN values in 'Choice Description' column with "Unknown"
chipotle_df['choice_description'].fillna('Unknown', inplace=True)

# Verify that the missing values have been handled
print("\nAfter Handling Missing Values:")
print(chipotle_df.isnull().sum())

1. Missing Values: Check for missing values in each column (Order ID, Quantity, Item Name, Choice Description, Item Price). How should missing values be handled?

In [35]:
# Check for missing values in each column
missing_values = chipotle_df.isnull().sum()
print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [36]:
# Replace NaN values in 'Choice Description' column with "Unknown"
chipotle_df['choice_description'].fillna('Unknown', inplace=True)

In [37]:
print("\nAfter Handling Missing Values:")
print(chipotle_df.isnull().sum())

After Handling Missing Values:
order_id              0
quantity              0
item_name             0
choice_description    0
item_price            0
dtype: int64

2. Data Types: Verify the data types of each column. Do they align with their expected types, and should any adjustments be made?

In [39]:
print(chipotle_df.dtypes)

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [40]:
# Convert 'Item Price' to a numeric
chipotle_df['item_price'] = chipotle_df['item_price'].str.replace('$', '').astype(float)

<ipython-input-40-6418e35f01d5>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  chipotle_df['item_price'] = chipotle_df['item_price'].str.replace('$', '').astype(float)

In [41]:
print(chipotle_df.dtypes)

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

3. Duplicated Entries: Identify and handle duplicated entries in the dataset. How might duplicates impact analysis, and what is the appropriate action?

In [44]:
duplicated_entries = chipotle_df[chipotle_df.duplicated()]

print("Duplicated Entries: ")
print(duplicated_entries)

Duplicated Entries:
      order_id  quantity                            item_name  \
238        103         1                        Steak Burrito
248        108         1                          Canned Soda
297        129         1                        Steak Burrito
381        165         1                    Canned Soft Drink
484        205         1                         Chicken Bowl
567        233         1                    Canned Soft Drink
617        254         1                                Chips
684        282         1                    Canned Soft Drink
773        319         1                         Chicken Bowl
908        376         1                        Steak Burrito
924        381         1                   Chicken Soft Tacos
1003       412         1                        Bottled Water
1117       462         1                      Chicken Burrito
1203       491         1                      Chicken Burrito
1245       507         1                    Canned Soft Drink
1381       561         1                    Canned Soft Drink
1410       573         1                        Bottled Water
1420       576         1                        Barbacoa Bowl
1421       576         1                  Barbacoa Salad Bowl
1502       610         1                      Chicken Burrito
1534       624         1  Chips and Tomatillo-Red Chili Salsa
1548       628         1                  Chips and Guacamole
1612       651         1                                 Izze
1791       724         1                    Canned Soft Drink
1792       724         1                    Canned Soft Drink
2078       838         1                   Chicken Soft Tacos
2127       856         1                      Chicken Burrito
2307       926         1                         Chicken Bowl
2318       926         1                         Chicken Bowl
2362       940         1                    Canned Soft Drink
2448       972         1                         Chicken Bowl
2553      1011         1                    Canned Soft Drink
2554      1011         1                    Canned Soft Drink
2560      1013         1                  Chips and Guacamole
2576      1020         1  Chips and Tomatillo Red Chili Salsa
2662      1057         1                   Chicken Soft Tacos
2708      1074         1                                Chips
2717      1078         1                         Chicken Bowl
2833      1125         1                      Chicken Burrito
2881      1144         1                        Bottled Water
2973      1182         1                         Chicken Bowl
2977      1184         1                           Steak Bowl
3121      1244         1                  Chips and Guacamole
3430      1377         1  Chips and Tomatillo Red Chili Salsa
3637      1454         1                   Chicken Soft Tacos
3716      1484         1                          Canned Soda
3764      1507         1                      Chicken Burrito
3829      1534         1                      Chicken Burrito
3924      1574         1                        Bottled Water
4112      1647         1                         Chicken Bowl
4155      1660         1                  Chips and Guacamole
4236      1691         1                         Chicken Bowl
4266      1701         1                                Chips
4372      1745         1                  Chips and Guacamole
4463      1778         1                    Canned Soft Drink
4479      1785         1                        Bottled Water
4544      1806         1                        Bottled Water
4570      1817         1                        Bottled Water
4603      1827         1                     Barbacoa Burrito

                                     choice_description  item_price
238   [Tomatillo Red Chili Salsa, [Rice, Black Beans...       11.75
248                                      [Mountain Dew]        1.09
297   [Tomatillo Green Chili Salsa, [Rice, Cheese, G...       11.75
381                                              [Coke]        1.25
484   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...        8.75
567                                         [Diet Coke]        1.25
617                                             Unknown        2.15
684                                              [Coke]        1.25
773   [Tomatillo-Green Chili Salsa (Medium), Black B...        8.49
908   [Roasted Chili Corn Salsa (Medium), [Rice, Faj...        8.99
924           [Tomatillo-Red Chili Salsa (Hot), Cheese]        8.49
1003                                            Unknown        1.50
1117  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.25
1203  [Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...        8.75
1245                                         [Lemonade]        1.25
1381                                             [Coke]        1.25
1410                                            Unknown        1.50
1420                         [Roasted Chili Corn Salsa]        9.25
1421                         [Roasted Chili Corn Salsa]        9.39
1502  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...        8.75
1534                                            Unknown        2.39
1548                                            Unknown        4.45
1612                                       [Blackberry]        3.39
1791                                             [Coke]        1.25
1792                                             [Coke]        1.25
2078  [Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...        8.75
2127  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.25
2307  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75
2318  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75
2362                                             [Coke]        1.25
2448  [Tomatillo Red Chili Salsa, [Rice, Black Beans...        8.75
2553                                             [Coke]        1.25
2554                                             [Coke]        1.25
2560                                            Unknown        4.45
2576                                            Unknown        2.95
2662  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.25
2708                                            Unknown        2.15
2717  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.25
2833      [Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]        8.75
2881                                            Unknown        1.50
2973  [Tomatillo-Red Chili Salsa (Hot), [Rice, Black...        8.49
2977  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...        9.25
3121                                            Unknown        4.45
3430                                            Unknown        2.95
3637                         [Fresh Tomato Salsa, Rice]        8.75
3716                                       [Dr. Pepper]        1.09
3764  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        8.75
3829  [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...        8.75
3924                                            Unknown        1.50
4112  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25
4155                                            Unknown        4.45
4236                                       [White Rice]        8.50
4266                                            Unknown        2.15
4372                                            Unknown        4.45
4463                                         [Lemonade]        1.25
4479                                            Unknown        1.50
4544                                            Unknown        1.50
4570                                            Unknown        1.50
4603                      [Tomatillo Green Chili Salsa]        9.25

In [45]:
print("count of duplicated entries",len(duplicated_entries))

count of duplicated entries 59

In [46]:
# Remove duplicated entries
chipotle_df.drop_duplicates(inplace=True)
print(chipotle_df)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description  item_price
0                                               Unknown        2.39
1                                          [Clementine]        3.39
2                                               [Apple]        3.39
3                                               Unknown        2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98
...                                                 ...         ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75

[4563 rows x 5 columns]

4. Quantity and Item Price: Question: Examine the Quantity and Item Price columns. Are there any inconsistencies or anomalies that need correction?

In [47]:
# Check data types of Quantity and Item Price columns
print("Data Types:")
print(chipotle_df[['quantity', 'item_price']].dtypes)

Data Types:
quantity        int64
item_price    float64
dtype: object

In [50]:
print("\nAnomalies in Quantity:")
print(chipotle_df[chipotle_df['quantity'] < 0])
print("\nAnomalies in Item Price:")
print(chipotle_df[chipotle_df['item_price'] <= 0])

Anomalies in Quantity:
Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price]
Index: []

Anomalies in Item Price:
Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price]
Index: []

In [51]:
print(chipotle_df[['quantity', 'item_price']].describe())

          quantity   item_price
count  4563.000000  4563.000000
mean      1.076704     7.490083
std       0.412739     4.244155
min       1.000000     1.090000
25%       1.000000     3.750000
50%       1.000000     8.750000
75%       1.000000     9.250000
max      15.000000    44.250000

5. Choice Description: Analyze the Choice Description column. How should choices be handled, especially when there are multiple descriptions for a single item?

In [52]:
choices = chipotle_df['choice_description'].str.split(', ')

In [54]:
# Create a new DataFrame with each choice as a separate row
choices_df = choices.explode().reset_index(drop=True)
print(choices,choices_df,end="\n")

0                                               [Unknown]
1                                          [[Clementine]]
2                                               [[Apple]]
3                                               [Unknown]
4       [[Tomatillo-Red Chili Salsa (Hot), [Black Bean...
                              ...
4617    [[Fresh Tomato Salsa, [Rice, Black Beans, Sour...
4618    [[Fresh Tomato Salsa, [Rice, Sour Cream, Chees...
4619    [[Fresh Tomato Salsa, [Fajita Vegetables, Pint...
4620    [[Fresh Tomato Salsa, [Fajita Vegetables, Lett...
4621    [[Fresh Tomato Salsa, [Fajita Vegetables, Pint...
Name: choice_description, Length: 4563, dtype: object 0                                 Unknown
1                            [Clementine]
2                                 [Apple]
3                                 Unknown
4        [Tomatillo-Red Chili Salsa (Hot)
                       ...
16839                           Lettuce]]
16840                 [Fresh Tomato Salsa
16841                  [Fajita Vegetables
16842                         Pinto Beans
16843                           Lettuce]]
Name: choice_description, Length: 16844, dtype: object

6. Handling Special Characters: Question: Check for special characters in text-based columns (e.g., Item Name, Choice Description). How can these be addressed for consistency?

In [55]:
import re

In [56]:
special_characters_pattern = r'[^a-zA-Z0-9\s]'
has_special_characters = chipotle_df['item_name'].str.contains(special_characters_pattern, regex=True)
# Remove or replace special characters in the Item Name column (example: replacing non-alphanumeric characters with a space)
chipotle_df['item_name'] = chipotle_df['item_name'].str.replace(special_characters_pattern, ' ')

<ipython-input-56-b50a291096a4>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  chipotle_df['item_name'] = chipotle_df['item_name'].str.replace(special_characters_pattern, ' ')

In [58]:
print(chipotle_df['item_name'].head(10))

0             Chips and Fresh Tomato Salsa
1                                     Izze
2                         Nantucket Nectar
3    Chips and Tomatillo Green Chili Salsa
4                             Chicken Bowl
5                             Chicken Bowl
6                            Side of Chips
7                            Steak Burrito
8                         Steak Soft Tacos
9                            Steak Burrito
Name: item_name, dtype: object

7. Order Id Integrity: Question: Cross-reference the Order ID column for integrity. Are there any irregularities or patterns that need validation?

In [59]:
unique_order_ids = chipotle_df['order_id'].nunique()
total_order_ids = chipotle_df.shape[0]
print("Number of Unique Order IDs:", unique_order_ids)
print("Total Order IDs:", total_order_ids)

Number of Unique Order IDs: 1834
Total Order IDs: 4563

In [60]:
# Check for non-numeric or irregularly formatted Order IDs
non_numeric_order_ids = chipotle_df[~chipotle_df['order_id'].astype(str).str.isdigit()]['order_id']
print("\nNon-Numeric or Irregularly Formatted Order IDs:")
print(non_numeric_order_ids)

Non-Numeric or Irregularly Formatted Order IDs:
Series([], Name: order_id, dtype: int64)

8. Item Name Standardization: Question: Standardize the Item Name column. Are there variations that can be unified for better analysis?

In [61]:
item_name_variations = chipotle_df['item_name'].value_counts()

In [62]:
# Create a mapping for standardization
name_mapping = {
    'Chips and Fresh Tomato Salsa': 'Chips and Salsa',
    'Chips and Tomatillo-Green Chili Salsa': 'Chips and Salsa',
    'Chips and Guacamole': 'Chips and Guac',
    'Chicken Bowl': 'Chicken Burrito Bowl',
    'Side of Chips': 'Chips',
    # Add more mappings as needed based on your observations
}

In [63]:
chipotle_df['item_name_standardized'] = chipotle_df['item_name'].replace(name_mapping)

In [64]:
print(chipotle_df[['item_name', 'item_name_standardized']])

                                  item_name  \
0              Chips and Fresh Tomato Salsa
1                                      Izze
2                          Nantucket Nectar
3     Chips and Tomatillo Green Chili Salsa
4                              Chicken Bowl
...                                     ...
4617                          Steak Burrito
4618                          Steak Burrito
4619                     Chicken Salad Bowl
4620                     Chicken Salad Bowl
4621                     Chicken Salad Bowl

                     item_name_standardized
0                           Chips and Salsa
1                                      Izze
2                          Nantucket Nectar
3     Chips and Tomatillo Green Chili Salsa
4                      Chicken Burrito Bowl
...                                     ...
4617                          Steak Burrito
4618                          Steak Burrito
4619                     Chicken Salad Bowl
4620                     Chicken Salad Bowl
4621                     Chicken Salad Bowl

[4563 rows x 2 columns]

9. Quantity and Price Relationships: Question: Investigate the relationships between Quantity and Item Price. Are there cases where adjustments need to be made for accurate analysis?

In [65]:
chipotle_df['Total Price'] = chipotle_df['quantity'] * chipotle_df['item_price']

In [66]:
zero_negative_values = chipotle_df[(chipotle_df['quantity'] <= 0) | (chipotle_df['item_price'] <= 0)]
print("Rows with Zero or Negative Values:")
print(zero_negative_values)

Rows with Zero or Negative Values:
Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price, item_name_standardized, Total Price]
Index: []

10. Data Integrity Check: Question: Perform a data integrity check by ensuring that quantities and prices align with the corresponding items and descriptions.

In [67]:
grouped_data = chipotle_df.groupby(['item_name', 'choice_description']).agg(
    Total_Quantity=('quantity', 'sum'),
    Total_Price=('item_price', lambda x: (x * chipotle_df['quantity']).sum())
).reset_index()

In [68]:
merged_df = pd.merge(chipotle_df, grouped_data, on=['item_name', 'choice_description'], suffixes=('', '_agg'))

data_integrity_check = merged_df[
    (merged_df['quantity'] != merged_df['Total_Quantity']) |
    (merged_df['item_price'] != merged_df['Total_Price'])
]

In [69]:
print("Rows with Quantity or Price Mismatch:")
print(data_integrity_check)

Rows with Quantity or Price Mismatch:
      order_id  quantity                     item_name  \
0            1         1  Chips and Fresh Tomato Salsa
1           13         1  Chips and Fresh Tomato Salsa
2           25         1  Chips and Fresh Tomato Salsa
3           39         1  Chips and Fresh Tomato Salsa
4           82         1  Chips and Fresh Tomato Salsa
...        ...       ...                           ...
4478      1719         2                 Steak Burrito
4514      1764         2                  Chicken Bowl
4515      1764         2                    Steak Bowl
4559      1830         1                 Steak Burrito
4560      1833         1                 Steak Burrito

                                     choice_description  item_price  \
0                                               Unknown        2.39
1                                               Unknown        2.39
2                                               Unknown        2.39
3                                               Unknown        2.95
4                                               Unknown        2.95
...                                                 ...         ...
4478  [Tomatillo Red Chili Salsa, [Rice, Black Beans...       18.50
4514  [Fresh Tomato Salsa, [Rice, Fajita Vegetables,...       22.50
4515  [Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...       23.50
4559  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75
4560  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75

     item_name_standardized  Total Price  Total_Quantity  Total_Price
0           Chips and Salsa         2.39             130      1033.96
1           Chips and Salsa         2.39             130      1033.96
2           Chips and Salsa         2.39             130      1033.96
3           Chips and Salsa         2.95             130      1033.96
4           Chips and Salsa         2.95             130      1033.96
...                     ...          ...             ...          ...
4478          Steak Burrito        37.00               2        37.00
4514   Chicken Burrito Bowl        45.00               2        45.00
4515             Steak Bowl        47.00               2        47.00
4559          Steak Burrito        11.75               2        23.50
4560          Steak Burrito        11.75               2        23.50

[3226 rows x 9 columns]

12. Handling Categorical Data: Question: For categorical columns (e.g., Item Name), consider encoding or transforming them into a format suitable for analysis.

In [71]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
chipotle_df['Item Name Encoded'] = label_encoder.fit_transform(chipotle_df['item_name'])
chipotle_df

,order_id,quantity,item_name,choice_description,item_price,item_name_standardized,Total Price,Item Name Encoded
0,1,1,Chips and Fresh Tomato Salsa,Unknown,2.39,Chips and Salsa,2.39,24
1,1,1,Izze,[Clementine],3.39,Izze,3.39,31
2,1,1,Nantucket Nectar,[Apple],3.39,Nantucket Nectar,3.39,32
3,1,1,Chips and Tomatillo Green Chili Salsa,Unknown,2.39,Chips and Tomatillo Green Chili Salsa,2.39,28
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,Chicken Burrito Bowl,33.96,17
...,...,...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,Steak Burrito,11.75,36
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,Steak Burrito,11.75,36
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,Chicken Salad Bowl,11.25,21
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,Chicken Salad Bowl,8.75,21
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,Chicken Salad Bowl,8.75,21

13. Consistent Quantity and Price Units: Question: Ensure consistency in units for Quantity and Item Price. Should any conversions or adjustments be made for uniform analysis?

In [72]:
 # Convert 'Quantity' to a uniform unit (e.g., pieces)
# Assuming 'Quantity' is in dozens, converting it to pieces by multiplying by 12
chipotle_df['quantity (pieces)'] = chipotle_df['quantity'] * 12

# Convert 'Item Price' to a single currency (e.g., USD)
# Assuming 'Item Price' is in EUR, convert it to USD using an exchange rate
exchange_rate = 1.12  # Example exchange rate from EUR to USD
chipotle_df['Item Price (USD)'] = chipotle_df['item_price'] * exchange_rate  # Convert EUR to USD
chipotle_df

,order_id,quantity,item_name,choice_description,item_price,item_name_standardized,Total Price,Item Name Encoded,quantity (pieces),Item Price (USD)
0,1,1,Chips and Fresh Tomato Salsa,Unknown,2.39,Chips and Salsa,2.39,24,12,2.6768
1,1,1,Izze,[Clementine],3.39,Izze,3.39,31,12,3.7968
2,1,1,Nantucket Nectar,[Apple],3.39,Nantucket Nectar,3.39,32,12,3.7968
3,1,1,Chips and Tomatillo Green Chili Salsa,Unknown,2.39,Chips and Tomatillo Green Chili Salsa,2.39,28,12,2.6768
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,Chicken Burrito Bowl,33.96,17,24,19.0176
...,...,...,...,...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,Steak Burrito,11.75,36,12,13.1600
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,Steak Burrito,11.75,36,12,13.1600
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,Chicken Salad Bowl,11.25,21,12,12.6000
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,Chicken Salad Bowl,8.75,21,12,9.8000
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,Chicken Salad Bowl,8.75,21,12,9.8000